### ISSUE TITLE
Troubleshoot Inspector

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#947]
##admins-github - <https://github.com/18F/usda-fns-ingest|18F/usda-fns-ingest> has vulnerabilities, but I wasn't able to find a corresponding channel.
ERROR for 18F/10x-MLaaS: Error: An API error occurred: channel_not_found
    at Object.platformErrorFromResult (/Users/alyssafeola/Documents/github/tts-tech-portfolio/inspector/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/Users/alyssafeola/Documents/github/tts-tech-portfolio/inspector/node_modules/@slack/web-api/dist/WebClient.js:152:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async notifyChannel (/Users/alyssafeola/Documents/github/tts-tech-portfolio/inspector/pr-nudges.js:128:3)
    at async handleVulnerabilities (/Users/alyssafeola/Documents/github/tts-tech-portfolio/inspector/pr-nudges.js:148:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'channel_not_found',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}

**Comment by afeld** [comment]
Narrowed this down a bit: Inspector (at least sometimes) is trying to join archived channels, which happens because the search API doesn't include `is_archived` in [the response](https://api.slack.com/methods/search.messages#response) 😒
